name: CI

on:
  push:
    branches: [master, develop]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20" # You can change this to your project's Node.js version

      - name: Install dependencies
        run: npm ci # Using npm ci for clean installs in CI environment

      - name: Build check
        run: npm run build

      - name: Check build output
        run: |
          if [ -d "dist" ]; then
            echo "Build succeeded and output directory exists!"
          else
            echo "Build output directory not found!"
            exit 1
          fi
